### ISSUE TITLE
Plugin fails to load when IDE started using packaged JVM

### ISSUE THREAD

**Issue by 0legg** [0legg/lottie-idea#1]
`javafx/scene/web/WebEngine
java.lang.NoClassDefFoundError: javafx/scene/web/WebEngine
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6218)
	at java.awt.Component.access$500(Component.java:186)
	at java.awt.Component$3.run(Component.java:6172)
	at java.awt.Component$3.run(Component.java:6170)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Component.checkCoalescing(Component.java:6169)
	at java.awt.Component.<init>(Component.java:6138)
	at java.awt.Container.<init>(Container.java:283)
	at javax.swing.JComponent.<init>(JComponent.java:588)
	at javax.swing.JPanel.<init>(JPanel.java:82)
	at javax.swing.JPanel.<init>(JPanel.java:95)
	at com.intellij.ui.components.JBPanel.<init>(JBPanel.java:43)
	at net.olegg.bodylookin.toolwindow.BodylookinView.<init>(BodylookinView.kt:19)
	at net.olegg.bodylookin.toolwindow.BodylookinFactory.createToolWindowContent(BodylookinFactory.kt:14)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:583)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$12.run(ToolWindowManagerImpl.java:562)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: javafx.scene.web.WebEngine PluginClassLoader[net.olegg.bodylookin, 0.0.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more`

**Comment by 0legg** [comment]
Fixed in https://github.com/0legg/bodylookin/commit/42adc74ee6157d1ef89a3605fa3a907ac912836b
